{"id": 3779, "title": "Ticket #3779: Shadow exception ubuntu 12", "description": "<blockquote>\nUbuntu12 and out kill test result in a shadow exception. Does not look right to me.\n\n<p>job_basic_kill.run\n\n</p><p></p><div class=\"code\">\n<pre class=\"code\">07/15/13 00:52:31 ******************************************************\n07/15/13 00:52:31 ** condor_shadow (CONDOR_SHADOW) STARTING UP\n07/15/13 00:52:31 ** /slots/04/dir_6291/userdir/condor/sbin/condor_shadow\n07/15/13 00:52:31 ** SubsystemInfo: name=SHADOW type=SHADOW(6) class=DAEMON(1)\n07/15/13 00:52:31 ** Configuration: subsystem:SHADOW local:&lt;NONE&gt; class:DAEMON\n07/15/13 00:52:31 ** $CondorVersion: 8.1.1 Jul 12 2013 BuildID: 148142 PRE-RELEASE-UWCS $\n07/15/13 00:52:31 ** $CondorPlatform: x86_64_Ubuntu12 $\n07/15/13 00:52:31 ** PID = 12164\n07/15/13 00:52:31 ** Log last touched 7/15 00:52:12\n07/15/13 00:52:31 ******************************************************\n07/15/13 00:52:31 Using config source: /slots/04/dir_6291/userdir/condor_tests/job_basic_kill.saveme/5180/5180basickill/condor_config\n07/15/13 00:52:31 Using local config sources:\n07/15/13 00:52:31    /slots/04/dir_6291/userdir/condor_tests/job_basic_kill.saveme/5180/5180basickill/condor_config.local\n07/15/13 00:52:31 DaemonCore: command socket at &lt;128.104.103.110:64786?noUDP&gt;\n07/15/13 00:52:31 DaemonCore: private command socket at &lt;128.104.103.110:64786&gt;\n07/15/13 00:52:31 Initializing a VANILLA shadow for job 2.0\n07/15/13 00:52:31 (2.0) (12164): Request to run on slot3@exec-110.batlab.org &lt;128.104.103.110:27219&gt; was ACCEPTED\n07/15/13 00:52:31 (2.0) (12164): Can't open directory \"/slots/04/dir_6291/userdir/condor_tests/job_basic_kill.saveme/5180/5180basickill/spool/2/0/cluster2.proc0.subproc0.tmp\" as PRIV_USER, errno: 2 (No such file or directory)\n07/15/13 00:52:31 (2.0) (12164): Can't open directory \"/slots/04/dir_6291/userdir/condor_tests/job_basic_kill.saveme/5180/5180basickill/spool/2/0/cluster2.proc0.subproc0\" as PRIV_USER, errno: 2 (No such file or directory)\n07/15/13 00:52:31 (2.0) (12164): Can't open directory \"/slots/04/dir_6291/userdir/condor_tests/job_basic_kill.saveme/5180/5180basickill/spool/2/0/cluster2.proc0.subproc0.tmp\" as PRIV_USER, errno: 2 (No such file or directory)\n07/15/13 00:52:31 (2.0) (12164): Can't open directory \"/slots/04/dir_6291/userdir/condor_tests/job_basic_kill.saveme/5180/5180basickill/spool/2/0/cluster2.proc0.subproc0\" as PRIV_USER, errno: 2 (No such file or directory)\n07/15/13 00:52:31 (2.0) (12164): File transfer completed successfully.\n07/15/13 00:52:33 (2.0) (12164): Requesting graceful removal of job.\n07/15/13 00:52:41 (2.0) (12164): condor_write(): Socket closed when trying to write 13 bytes to startd slot3@exec-110.batlab.org, fd is 5\n07/15/13 00:52:41 (2.0) (12164): Buf::write(): condor_write() failed\n07/15/13 00:52:41 (2.0) (12164): ERROR \"Assertion ERROR on (result)\" at line 789 in file /slots/01/dir_10228/userdir/src/condor_shadow.V6.1/NTreceivers.cpp\n</pre></div>\n</blockquote>", "remarks": "<blockquote>\n</blockquote>", "derived_tickets": "", "attachments": "", "check_ins": "", "type": "defect", "last_change": "2016-Dec-09 10:44", "status": "new", "created": "2013-Jul-15 12:05", "fixed_version": "2013-Jul-15 12:05", "broken_version": "v080100", "priority": "4", "subsystem": "DaemonsSubmitNode", "assigned_to": "tannenba", "derived_from": "", "creator": "bt", "rust": "", "customer_group": "other", "visibility": "public", "notify": "bt@cs.wisc.edu,johnkn@cs.wisc.edu", "due_date": ""}