{"id": 6985, "title": "Ticket #6985: multifile curl plugin never retries", "description": "<blockquote>\nThe multi-file curl plugin never retries.</blockquote>", "remarks": "<blockquote>\n<em>2019-Apr-10 11:21:19 by tim:</em> <br/>\n\nUnrleased bug. No version history.</blockquote>", "derived_tickets": "", "attachments": "", "check_ins": "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n<tbody><tr><td align=\"right\" valign=\"top\" width=\"160\">2019-Apr-10 11:22</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"chngview?cn=56561\">[56561]</a></span>: Use the error code, not retry number. <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=6985\" onclick=\"get_ticket_and_populate_wrapper('6985'); return false;\" title=\"multifile curl plugin never retries\">#6985</a></span> The curl plugin appears to have a frustrating bug that, when it checks the exit code for a failure that should be retried, it doesn't actually check the exit code - rather, it checks the retry number!\u00a0[...]\n (By Brian Bockelman )</td></tr>\n</tbody></table>", "type": "defect", "last_change": "2019-Apr-10 13:49", "status": "resolved", "created": "2019-Apr-10 11:21", "fixed_version": "2019-Apr-10 11:21", "broken_version": "v080901", "priority": "1", "subsystem": "FileTransfer", "assigned_to": "tim", "derived_from": "#6971", "creator": "tim", "rust": "", "customer_group": "chtc", "visibility": "public", "notify": "", "due_date": ""}