{"id": 4431, "title": "Ticket #4431: Poor error message from condor_ping", "description": "<blockquote>\nWe had a user report the following issue:\n\n<p></p><div class=\"verbatim\">\n<pre>#  condor_ce_ping -pool 'osg-gw-4.t2.ucsd.edu' -name 'osg-gw-4.t2.ucsd.edu' -table READ WRITE DAEMON\nERROR: couldn't locate osg-gw-4.t2.ucsd.edu!\n</pre></div>\n\n\n<p>This made him think the schedd was not reporting.  However, if you add the \"-debug\" flag, you got:\n\n</p><p></p><div class=\"verbatim\">\n<pre>$ condor_ce_ping -debug -pool osg-gw-4.t2.ucsd.edu -name osg-gw-4.t2.ucsd.edu\nWARNING: Missing &lt;authz-level | command-name | command-int&gt; argument, defaulting to DC_NOP\n06/30/14 20:44:12 recognized DC_NOP as command name, using command 60011.\n06/30/14 20:44:12 attempt to connect to &lt;169.228.130.18:9618&gt; failed: No route to host (connect errno = 113).\nERROR: couldn't locate osg-gw-4.t2.ucsd.edu!\n</pre></div>\n\n\n<p>This makes it clear there is a issue contacting the collector.\n\n</p><p>Can the error message be improved?  The condor_status client handled this error well.</p></blockquote>", "remarks": "<blockquote>\n</blockquote>", "derived_tickets": "", "attachments": "", "check_ins": "", "type": "incident", "last_change": "2014-Jun-30 21:20", "status": "new", "created": "2014-Jun-30 21:20", "fixed_version": "2014-Jun-30 21:20", "broken_version": "", "priority": "3", "subsystem": "Tools", "assigned_to": "zmiller", "derived_from": "", "creator": "bbockelm", "rust": "", "customer_group": "osg", "visibility": "public", "notify": "bbockelm@cse.unl.edu", "due_date": ""}