{"id": 7808, "title": "Ticket #7808: from_dag() binding should throw exception when .dag file not found", "description": "<blockquote>\nThe <code>htcondor.Submit.from_dag()</code> python binding outputs an error when the specified .dag file does not exist, but it does not throw an exception. We should change this so it throws a <span class=\"wiki\"><a class=\"missing\" href=\"wiki?p=RuntimeError\" title=\"Runtime Error\">RuntimeError</a></span> exception, which the user can catch and handle appropriately.</blockquote>", "remarks": "<blockquote>\n<em>2020-Aug-21 08:28:13 by karpel:</em> <br/>\n\nCan this be a <code>FileNotFound</code> exception so that its more specific?\n\n<p></p><hr/>\n<em>2020-Aug-21 10:11:33 by tlmiller:</em> <br/>\n\nSee <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=6935\" onclick=\"get_ticket_and_populate_wrapper('6935'); return false;\" title=\"Unexpected exceptions in Python bindings\">#6935</a></span> for why the answer is yes.  (OK, I just noticed that this ticket is (a) derived from that one and (b) points to the RUST where the user made this request.)\n\n<p></p><hr/>\n<em>2020-Aug-21 13:39:00 by coatsworth:</em> <br/>\n\nSure, I can rewire this to throw more specific exceptions. It's a bit of extra work because the Python binding is built on the <code>dagman_utils</code> library which is shared with the <code>condor_dagman</code> CLI, but it seems pretty trivial to actually hook this in, so I'll plan on it.</blockquote>", "derived_tickets": "", "attachments": "", "check_ins": "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n<tbody><tr><td align=\"right\" valign=\"top\" width=\"160\">2020-Oct-02 12:56</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"chngview?cn=61404\">[61404]</a></span>: Added version history (<span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=7808\" onclick=\"get_ticket_and_populate_wrapper('7808'); return false;\" title=\"from_dag() binding should throw exception when .dag file not found\">#7808</a></span>)  (By Mark Coatsworth )</td></tr>\n<tr><td align=\"right\" valign=\"top\" width=\"160\">2020-Aug-26 13:55</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"chngview?cn=60556\">[60556]</a></span>: DAGMan python binding now throws IOErrors with errno for file-related errors (<span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=7808\" onclick=\"get_ticket_and_populate_wrapper('7808'); return false;\" title=\"from_dag() binding should throw exception when .dag file not found\">#7808</a></span>)  (By Mark Coatsworth )</td></tr>\n</tbody></table>", "type": "defect", "last_change": "2020-Oct-07 14:19", "status": "resolved", "created": "2020-Aug-20 16:46", "fixed_version": "2020-Aug-20 16:46", "broken_version": "v080903", "priority": "3", "subsystem": "PythonBinding", "assigned_to": "coatsworth", "derived_from": "#6935", "creator": "coatsworth", "rust": "s101297", "customer_group": "other", "visibility": "public", "notify": "karpel@wisc.edu", "due_date": ""}