{"id": 91, "title": "Ticket #91: PrivSep: Create_Process errors do not result in job being held", "description": "<blockquote>\nIn the Starter, we respond to certain failure conditions by placing the job on hold. Examples include the executable not being found or not having execute permission (i.e. ENOENT or EACCES from exec()). When <span class=\"wiki\"><a href=\"wiki?p=PrivSep\" title=\"Priv Sep\">PrivSep</a></span> is enabled on the execute-machine, some of these types of failures do not have this effect.</blockquote>", "remarks": "<blockquote>\n</blockquote>", "derived_tickets": "", "attachments": "<html><head></head><body></body></html>", "check_ins": "", "type": "defect", "last_change": "2010-Jan-31 13:20", "status": "new", "created": "2009-Jan-23 16:47", "fixed_version": "2009-Jan-23 16:47", "broken_version": "", "priority": "4", "subsystem": "Security", "assigned_to": "zmiller", "derived_from": "", "creator": "gquinn", "rust": "", "customer_group": "other", "visibility": "public", "notify": "", "due_date": ""}