{"id": 3357, "title": "Ticket #3357: startd crash at LIGO", "description": "<blockquote>\ncondor_startd version 7.8.6 has crashed with exit status 1 on the following system,\n\n<p></p><div class=\"verbatim\">\n<pre>[root@node359 condor]# condor_version\n$CondorVersion: 7.8.6 Oct 24 2012 BuildID: 73238 $\n$CondorPlatform: x86_64_rhap_6.3 $\n</pre></div>\n\n\n<p>with the following stack trace,\n</p><div class=\"verbatim\">\n<pre>(gdb) where\n#0  0x0000000000454d94 in WriteCoreDump ()\n#1  0x00007fc76df5f498 in linux_sig_coredump(int) () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#2  &lt;signal handler called&gt;\n#3  0x00007fc76de43290 in passwd_cache::get_groups(char const*, unsigned long, unsigned int*) () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#4  0x00007fc76de43416 in passwd_cache::init_groups(char const*, unsigned int) () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#5  0x00007fc76de39989 in _set_priv () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#6  0x00007fc76de92a27 in _condor_dprintf_va () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#7  0x00007fc76de32788 in dprintf () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#8  0x00007fc76de434d9 in passwd_cache::init_groups(char const*, unsigned int) () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#9  0x00007fc76de39989 in _set_priv () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#10 0x00007fc76df808ab in DaemonCore::Create_Process(char const*, ArgList const&amp;, priv_state, int, int, Env const*, char const*, FamilyInfo*, Stream**, int*, int*, int, __sigset_t*, int, unsigned long*, int*, char const*, MyString*, FilesystemRemap*) () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#11 0x00007fc76debc579 in CronJob::StartJobProcess() () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#12 0x00007fc76de4701b in CondorCronJobList::StartOnDemandJobs() () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#13 0x00007fc76ded291d in CronJobMgr::StartOnDemandJobs() () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#14 0x00000000004323d3 in StartdBenchJobMgr::StartBenchmarks(Resource*, int&amp;) ()\n#15 0x000000000043dcce in MachAttributes::start_benchmarks(Resource*, int&amp;) ()\n#16 0x000000000042e208 in ResState::eval() ()\n#17 0x000000000042d8f6 in ResState::enter_action(State, Activity, bool, bool) ()\n#18 0x000000000042cfa6 in ResState::change(State, Activity) ()\n#19 0x000000000044376c in Resource::leave_preempting_state() ()\n#20 0x000000000042db08 in ResState::enter_action(State, Activity, bool, bool) ()\n#21 0x000000000042cfa6 in ResState::change(State, Activity) ()\n#22 0x000000000042e0c9 in ResState::eval() ()\n#23 0x000000000044c94c in reaper(Service*, int, int) ()\n#24 0x00007fc76df7171c in DaemonCore::CallReaper(int, char const*, int, int) () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#25 0x00007fc76df78109 in DaemonCore::HandleProcessExit(int, int) () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#26 0x00007fc76df782e9 in DaemonCore::HandleDC_SERVICEWAITPIDS(int) () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#27 0x00007fc76df7a3a4 in DaemonCore::Driver() () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#28 0x00007fc76df60db0 in dc_main(int, char**) () from /usr/lib64/condor/libcondor_utils_7_8_6.so\n#29 0x0000003fd1a1ecdd in __libc_start_main () from /lib64/libc.so.6\n#30 0x0000000000421339 in _start ()\n</pre></div>\n</blockquote>", "remarks": "<blockquote>\n<em>2012-Dec-06 07:41:47 by bbockelm:</em> <br/>\n\nDid they have any startd plugins (i.e., QMF?) enabled?  I'd expect something like that if there were multiple threads (Create_Process CANNOT be called when there are other threads active!).\n\n<p></p><hr/>\n<em>2012-Dec-06 11:02:55 by zmiller:</em> <br/>\n\ni don't know about the plugins, but i think i've narrowed it down to something else anyways.  at some point in frame 8 or 9, getgroups() fails, which in this instance causes condor to wig out.  still working out exactly what happened.\n\n<p></p><hr/>\n<em>2012-Dec-06 12:07:14 by bbockelm:</em> <br/>\n\nAh, missed that the segfault was in libcondor_utils, not glibc.  So, it's probably something more mundane.\n\n<p></p><hr/>\n<em>2012-Dec-11 15:52:55 by zmiller:</em> <br/>\n\naccording to gdb, the password cache had a corrupt entry.  it's not yet clear to me if this is caused by re-entering _set_priv or if it was already corrupted before the first call.\n\n<p>i'll post the full gdb strack trace with debug symbols as soon as their machine is back online.\n\n</p><p></p><hr/>\n<em>2012-Dec-17 12:59:30 by zmiller:</em> <br/>\n\nLIGO has said this is a one-off and currently not a high priority for them.\n<hr/>\n<em>2012-Dec-19 09:30:47 by johnkn:</em> <br/>\n\nBulk change of target version from v070807 to v070808 using ./ticket-target-mover.\n<hr/>\n<em>2013-Mar-28 17:16:00 by johnkn:</em> <br/>\n\nBulk change of target version from v070808 to v070809 using ./ticket-target-mover.\n\n<p></p><hr/>\n<em>2013-May-28 14:45:18 by gthain:</em> <br/>\n\nAs LIGO has only seen this once, and we can't reproduce this, we'll mark this as stalled.\n\n<p></p><hr/>\n<em>2013-Jul-15 16:42:04 by zmiller:</em> <br/>\n\nThis bug was reported again in another ticket, <span class=\"ticket\"><a class=\"resolved\" href=\"/wiki-archive/tickets/?ticket=3723\" onclick=\"get_ticket_and_populate_wrapper('3723'); return false;\" title=\"Frequent shadow crashes on CMS machine at CERN\">#3723</a></span></blockquote>", "derived_tickets": "", "attachments": "<html><head></head><body></body></html>", "check_ins": "", "type": "defect", "last_change": "2013-Sep-16 09:28", "status": "defer", "created": "2012-Dec-04 14:49", "fixed_version": "2012-Dec-04 14:49", "broken_version": "v070806", "priority": "5", "subsystem": "Daemons", "assigned_to": "zmiller", "derived_from": "", "creator": "zmiller", "rust": "", "customer_group": "ligo", "visibility": "public", "notify": "tstclair@redhat.com,pcouvare@caltech.edu", "due_date": ""}